### ISSUE TITLE
Ability to change baud up and down, 9600 - 38400 - 9600

### ISSUE THREAD

**Issue by nzmCoder** [nmoulton1968/GarminBinary#11]
Right now the program can change the baud from the default rate of 9600 to one hard coded higher rate, currently 115200. It can not change back to 9600, nor can it select among multiple rates. This means that when the rate has been increased, the only way for the PC and GPS to get back to 9600 is to restart the GPS (or go into settings and change the interface to non-Garmin, then back to Garmin), and restart the PC program.

**Comment by nmoulton1968** [comment]
Right now the program can change the baud from the default rate of 9600 to one hard coded higher rate, currently 115200. It can not change back to 9600, nor can it select among multiple rates.  This means that when the rate has been increased, the only way for the PC and GPS to get back to 9600 is to restart the GPS (or go into settings and change the interface to non-Garmin, then back to Garmin), and restart the PC program.

**Comment by nzmCoder** [comment]
After playing with this for a few days, I think 38400 baud is all we need.  I have figured out that turning on only partial async events, using mask 0x2000 enables messages 36, 37, 38. As an additional optional step we can turn on message 33 using the separate command.  We can then have only messages 33, 36, 37, and 38 emitted during async running.  With this, we seem to have enough bandwidth at 38400.  This has been tested also with GPS V and seems to work.

**Comment by nzmCoder** [comment]
To summarize, all we need is to go back and forth from 9600 to 38400 to 9600 . . .

**Comment by nzmCoder** [comment]
Staying away from the highest rate, 115200, avoids the problem of the eTrex turning off satellite reception, too.

**Comment by nzmCoder** [comment]
After playing with this a few more days, I think 57600 is the best answer.  I have implemented the ability to change the GPS baud up and down.  The baud confirmation function is now agnostic to the baud rate that was set, it works to confirm any possible baud that it set, so the only thing to change is the initial baud in the set baud command.  Also added a "sync" button to get back in sync with the GPS baud if the program leaves it in high baud, for example. With these 3 controls added, up, down, sync, I say this feature is done.
Closed.
