### ISSUE TITLE
State machine to perform the steps to create G12 file

### ISSUE THREAD

**Issue by nzmCoder** [nmoulton1968/GarminBinary#17]
1. Ask user for file name and path to create G12 output file.
2. Set baud to 57600 if not already.
3. Request GPS identity, response message 0xFF.
4. Query position, response messgae 0x11.
5. Query UTC Time, response message 0x0E.
6. Turn on One per second PVT messages, 0x33.
7. Wait to see at least 5 PVT messages with fix quality 3 or better.
8. Turn off PVT messages.
9. Enable async messages. Record messages 0x36, 0x37, 0x38.
10. Keep going until user hits a Stop button.
11. Spawn a command console, launch gar2rnx, process file to Rinex.
12. Rename rinex file to modern naming standards: siteXXXA.YYo

**Comment by nmoulton1968** [comment]
1.Set baud to 57600 if not already.
2. Ask user for file name and path to create G12 output file.
3.Request GPS identity, response message 0xFF.
4.Query position, response messgae 0x11.
5.Query UTC Time, response message 0x0E.
6.Turn on One per second PVT messages, 0x33.
7.Wait to see at least 5 PVT messages with fix quality 3 or better.
8. Turn off PVT messages.
9.Enable async messages. Record messages 0x36, 0x37, 0x38.
10. Keep going until user hits a Stop button.

**Comment by nzmCoder** [comment]
Many of these tasks are done.  The item remains open because some of the things are not done.

**Comment by nzmCoder** [comment]
Most items are done.  Created separate item to track outstanding sub-items in list, or decided not to do sub-items.  This larger issue is called done.
